language: ruby

sudo: false

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false -J-Xmx1g"

services:
  - redis

addons:
  postgresql: 9.3
  artifacts:
    paths:
    - log/

cache:
  directories:
    - vendor/bundle

sudo: false

rvm:
  - "2.0"
  - "2.1"

jdk: oraclejdk7

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-9.0.0.0

before_install:
  - if [ $TRAVIS_RUBY_VERSION = 'jruby-9.0.0.0' ]; then rvm get head; rvm use --install jruby-9.0.0.0; ruby --version; fi
  - gem install bundler -v 1.9.0

install:
  # JRuby fails to resolve dependencies on newer bundler
  - bundle _1.9.0_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

script:
  - ./build.sh
